#!/usr/bin/env bash
# ==============================================================
#  AccountFlow installer — Linux server (trial or production)
#  Usage:  bash install.sh
# ==============================================================
set -euo pipefail
cd "$(dirname "$0")"

step() { printf '\n\033[36m==> %s\033[0m\n' "$1"; }
good() { printf '    \033[32m%s\033[0m\n' "$1"; }
bad()  { printf '\n\033[31m!!  %s\033[0m\n' "$1"; }

rand_secret() { openssl rand -base64 48 | tr -d '+/=' | cut -c1-48; }
fernet_key()  { openssl rand -base64 32 | tr '+/' '-_'; }

echo "=========================================================="
echo "  AccountFlow installer (Linux)"
echo "=========================================================="

# ---------- 1. Docker check ----------
step "Checking Docker..."
if ! command -v docker >/dev/null 2>&1; then
    bad "Docker is not installed."
    echo "  Install it with:  curl -fsSL https://get.docker.com | sh"
    exit 1
fi
if ! docker info >/dev/null 2>&1; then
    bad "Docker is installed but not running (or you need sudo)."
    echo "  Try:  sudo systemctl start docker"
    echo "  Or run this script with sudo."
    exit 1
fi
good "Docker is running."

# ---------- 2. .env ----------
step "Setting up the configuration file..."
if [ -f .env ]; then
    good "Found an existing .env — keeping your settings."
    ADMIN_KEY=$(grep -oP '^DASHBOARD_API_KEY=\K.*' .env | tr -d '\r')
else
    echo
    echo "  The app uses Claude AI to read and draft emails."
    echo "  Get a key at https://console.anthropic.com (starts with sk-ant-)."
    echo "  Press Enter to skip and add it later."
    echo
    read -r -p "  Paste your Anthropic API key (or Enter to skip): " ANTHROPIC_KEY
    ANTHROPIC_KEY=${ANTHROPIC_KEY:-sk-ant-REPLACE-ME-LATER}

    DB_PASSWORD=$(rand_secret)
    APP_DB_PASSWORD=$(rand_secret)
    REDIS_PASSWORD=$(rand_secret)
    ADMIN_KEY=$(rand_secret)
    JWT_SECRET=$(rand_secret)
    FERNET=$(fernet_key)

    cat > .env << ENVEOF
# ---- Generated by install.sh on $(date '+%Y-%m-%d %H:%M') ----
POSTGRES_DB=accountflow
POSTGRES_USER=accountflow
POSTGRES_PASSWORD=${DB_PASSWORD}
# The app connects as accountflow_app (row-level security); Alembic as the owner.
DATABASE_URL=postgresql+asyncpg://accountflow_app:${APP_DB_PASSWORD}@db:5432/accountflow
MIGRATION_DATABASE_URL=postgresql+asyncpg://accountflow:${DB_PASSWORD}@db:5432/accountflow

REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

FERNET_KEY=${FERNET}
DASHBOARD_API_KEY=${ADMIN_KEY}
JWT_SECRET_KEY=${JWT_SECRET}

ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
AI_CONFIDENCE_THRESHOLD=0.85

# Fill these in later to connect Gmail (see INSTALL_GUIDE.md, Part 3)
GOOGLE_CLIENT_ID=not-set-yet
GOOGLE_CLIENT_SECRET=not-set-yet
GOOGLE_REDIRECT_URI=http://localhost:8000/api/auth/google/callback

# Optional — only needed for summary emails
SENDGRID_API_KEY=not-set-yet
SENDGRID_FROM_EMAIL=noreply@example.com
SENDGRID_FROM_NAME=AccountFlow

SENTRY_DSN=

ENVIRONMENT=development
GMAIL_POLL_INTERVAL=120
GMAIL_MAX_RESULTS=50
APP_BASE_URL=http://localhost:8000
ENVEOF
    good "Created .env with strong random passwords."
fi

# ---------- 3. Build and start ----------
step "Building and starting the app (first time takes a few minutes)..."
docker compose up -d --build db redis api worker beat
good "All services started."

# ---------- 4. Wait for health ----------
step "Waiting for the app to come online..."
HEALTHY=""
for _ in $(seq 1 30); do
    sleep 3
    if curl -fsS http://127.0.0.1:8000/api/health >/dev/null 2>&1; then HEALTHY=1; break; fi
done
if [ -z "$HEALTHY" ]; then
    bad "The app did not answer after 90 seconds. Check: docker compose logs api"
    exit 1
fi
good "The app is online."

# ---------- 5. Database ----------
step "Preparing the database..."
docker compose exec -T api alembic upgrade head
good "Database ready."

# ---------- 6. First account ----------
step "Creating your first login account..."
read -r -p "  Your business name: " BIZ_NAME
read -r -p "  Your email (this becomes your login): " BIZ_EMAIL
read -r -s -p "  Choose a password (12+ characters): " BIZ_PASS; echo
HTTP_CODE=$(curl -s -o /tmp/accountflow_tenant.json -w '%{http_code}' \
    -X POST http://127.0.0.1:8000/api/tenants \
    -H "X-API-Key: ${ADMIN_KEY}" -H "Content-Type: application/json" \
    -d "{\"name\":\"${BIZ_NAME}\",\"email\":\"${BIZ_EMAIL}\",\"password\":\"${BIZ_PASS}\",\"plan\":\"starter\"}")
if [ "$HTTP_CODE" = "201" ]; then
    good "Account created for ${BIZ_EMAIL}."
else
    bad "Could not create the account (HTTP ${HTTP_CODE}): $(cat /tmp/accountflow_tenant.json)"
    echo "  You can re-run this installer — existing settings are kept."
fi

echo
printf '\033[32m==========================================================\033[0m\n'
printf '\033[32m  DONE! AccountFlow is running.\033[0m\n'
printf '\033[32m==========================================================\033[0m\n'
echo
echo "  Try it now:  open http://localhost:8000/api/docs"
echo "  Next step:   connect Gmail — see INSTALL_GUIDE.md, Part 3."
echo
echo "  Everyday commands (run in this folder):"
echo "    stop:     docker compose down"
echo "    start:    docker compose up -d db redis api worker beat"
echo "    logs:     docker compose logs -f api"
echo
echo "  Going live on a real domain later? See INSTALL_GUIDE.md, Part 5."
