# ==============================================================
#  AccountFlow installer — local / trial mode (Windows)
#  Run via install.bat (double-click) or:
#    powershell -ExecutionPolicy Bypass -File install.ps1
# ==============================================================
$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot

function Write-Step($msg)  { Write-Host ""; Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Good($msg)  { Write-Host "    $msg" -ForegroundColor Green }
function Write-Bad($msg)   { Write-Host ""; Write-Host "!!  $msg" -ForegroundColor Red }

function New-RandomSecret {
    param([int]$NumBytes = 48)
    # RNGCryptoServiceProvider works on BOTH Windows PowerShell 5.1 and PowerShell 7+
    $bytes = New-Object byte[] $NumBytes
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $rng.GetBytes($bytes); $rng.Dispose()
    return ([Convert]::ToBase64String($bytes)) -replace '[+/=]', ''
}

function New-FernetKey {
    # Fernet requires exactly 32 random bytes, url-safe base64 encoded
    $bytes = New-Object byte[] 32
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $rng.GetBytes($bytes); $rng.Dispose()
    return [Convert]::ToBase64String($bytes).Replace('+','-').Replace('/','_')
}

Write-Host "=========================================================="
Write-Host "  AccountFlow installer  (local trial mode)"
Write-Host "  This will set up everything on this computer."
Write-Host "=========================================================="

# ---------- 1. Docker check ----------
Write-Step "Checking that Docker Desktop is installed and running..."
$dockerOk = $false
try {
    docker info *> $null
    if ($LASTEXITCODE -eq 0) { $dockerOk = $true }
} catch { }
if (-not $dockerOk) {
    Write-Bad "Docker Desktop is not running (or not installed)."
    Write-Host ""
    Write-Host "  1. Download it free from:  https://www.docker.com/products/docker-desktop/"
    Write-Host "  2. Install it, restart the computer if asked."
    Write-Host "  3. Open Docker Desktop and wait until it says 'Engine running'."
    Write-Host "  4. Run this installer again."
    exit 1
}
Write-Good "Docker is running."

# ---------- 2. Create the settings file (.env) ----------
Write-Step "Setting up the configuration file..."
if (Test-Path ".env") {
    Write-Good "Found an existing .env — keeping your settings."
    $envText  = Get-Content ".env" -Raw
    $adminKey = ([regex]::Match($envText, 'DASHBOARD_API_KEY=(.+)')).Groups[1].Value.Trim()
} else {
    Write-Host ""
    Write-Host "  The app uses Claude AI to read and draft emails."
    Write-Host "  You need one key for that. Get it at: https://console.anthropic.com"
    Write-Host "  (Sign up -> API Keys -> Create Key. It starts with sk-ant-)"
    Write-Host "  You can also press Enter to skip and add it later."
    Write-Host ""
    $anthropicKey = Read-Host "  Paste your Anthropic API key (or press Enter to skip)"
    if ([string]::IsNullOrWhiteSpace($anthropicKey)) { $anthropicKey = "sk-ant-REPLACE-ME-LATER" }

    $dbPassword    = New-RandomSecret 24
    $redisPassword = New-RandomSecret 24
    $adminKey      = New-RandomSecret 32
    $jwtSecret     = New-RandomSecret 48
    $fernetKey     = New-FernetKey

    @"
# ---- Generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm") ----
POSTGRES_DB=accountflow
POSTGRES_USER=accountflow
POSTGRES_PASSWORD=$dbPassword
DATABASE_URL=postgresql+asyncpg://accountflow:$dbPassword@db:5432/accountflow

REDIS_PASSWORD=$redisPassword
REDIS_URL=redis://:$redisPassword@redis:6379/0

FERNET_KEY=$fernetKey
DASHBOARD_API_KEY=$adminKey
JWT_SECRET_KEY=$jwtSecret

ANTHROPIC_API_KEY=$anthropicKey
AI_CONFIDENCE_THRESHOLD=0.85

# Fill these in later to connect Gmail (see INSTALL_GUIDE.md, Part 3)
GOOGLE_CLIENT_ID=not-set-yet
GOOGLE_CLIENT_SECRET=not-set-yet
GOOGLE_REDIRECT_URI=http://localhost:8000/api/auth/google/callback

# Optional — only needed for summary emails (see guide)
SENDGRID_API_KEY=not-set-yet
SENDGRID_FROM_EMAIL=noreply@example.com
SENDGRID_FROM_NAME=AccountFlow

SENTRY_DSN=

ENVIRONMENT=development
GMAIL_POLL_INTERVAL=120
GMAIL_MAX_RESULTS=50
APP_BASE_URL=http://localhost:8000
"@ | Set-Content -Path ".env" -Encoding ASCII
    Write-Good "Created .env with strong random passwords (saved in this folder)."
}

# ---------- 3. Build and start ----------
Write-Step "Building and starting the app (first time takes 3-10 minutes)..."
docker compose up -d --build db redis api worker beat
if ($LASTEXITCODE -ne 0) {
    Write-Bad "Something went wrong starting the app. Scroll up for the red error text."
    exit 1
}
Write-Good "All services started."

# ---------- 4. Wait until the app answers ----------
Write-Step "Waiting for the app to come online..."
$healthy = $false
for ($i = 0; $i -lt 30; $i++) {
    Start-Sleep -Seconds 3
    try {
        $r = Invoke-RestMethod -Uri "http://127.0.0.1:8000/api/health" -TimeoutSec 5
        if ($r.status) { $healthy = $true; break }
    } catch { }
}
if (-not $healthy) {
    Write-Bad "The app did not answer after 90 seconds."
    Write-Host "  See what went wrong with:  docker compose logs api"
    exit 1
}
Write-Good "The app is online."

# ---------- 5. Prepare the database ----------
Write-Step "Preparing the database..."
docker compose exec -T api alembic upgrade head
if ($LASTEXITCODE -ne 0) { Write-Bad "Database setup failed. Run: docker compose logs api"; exit 1 }
Write-Good "Database ready."

# ---------- 6. Create your login account ----------
Write-Step "Creating your first login account..."
$bizName  = Read-Host "  Your business name (e.g. Bright Smile Dental)"
$bizEmail = Read-Host "  Your email address (this will be your login)"
$bizPass  = Read-Host "  Choose a password (at least 12 characters)"
try {
    $body = @{ name = $bizName; email = $bizEmail; password = $bizPass; plan = "starter" } | ConvertTo-Json
    $tenant = Invoke-RestMethod -Uri "http://127.0.0.1:8000/api/tenants" -Method Post `
        -Headers @{ "X-API-Key" = $adminKey } -ContentType "application/json" -Body $body
    Write-Good "Account created for $($tenant.email)."
} catch {
    Write-Bad "Could not create the account: $($_.Exception.Message)"
    Write-Host "  (Password too short? Email already used? You can re-run this installer.)"
}

# ---------- Done ----------
Write-Host ""
Write-Host "=========================================================="  -ForegroundColor Green
Write-Host "  DONE! AccountFlow is running on this computer."             -ForegroundColor Green
Write-Host "=========================================================="  -ForegroundColor Green
Write-Host ""
Write-Host "  Try it now:   open  http://localhost:8000/api/docs  in your browser"
Write-Host "                (a page where you can click and test every function)"
Write-Host ""
Write-Host "  Log in there: use POST /api/auth/login with your email + password."
Write-Host ""
Write-Host "  Next step:    connect Gmail — see INSTALL_GUIDE.md, Part 3."
Write-Host ""
Write-Host "  Everyday commands (run in this folder):"
Write-Host "    stop the app:   docker compose down"
Write-Host "    start again:    docker compose up -d db redis api worker beat"
Write-Host "    see activity:   docker compose logs -f api"
